### ISSUE TITLE
Pypi file size limit

### ISSUE THREAD

**Issue by tbaudier** [OpenGATE/gam-gate#13]
After merging of gam-g4 and gam-gate, the wheels are too heavy (102 MB > 100 MB) so they cannot be uploaded on pypi.
I opened an issue to ask for an increase of the file size limit:
https://github.com/pypa/pypi-support/issues/1727

If we cannot to have an increment. Maybe we can try to separate the wheels:
https://stackoverflow.com/a/51300874

**Comment by dsarrut** [comment]
Done, thanks!
